set -g mouse on
set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -g set-clipboard on
set -g allow-passthrough on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# ayu-dark theme, transparent background
set -g status-style "bg=default,fg=#bfbdb6"
set -g status-left ""
set -g status-right "#[fg=#53bdfa,bg=default,bold] #S #[fg=default,bg=default]"
set -g window-status-style "fg=#686868,bg=default"
set -g window-status-current-style "fg=#f9af4f,bg=default,bold"
set -g window-status-format "#I:#{?window_zoomed_flag,󰊓 ,}#W"
set -g window-status-current-format "#I:#{?window_zoomed_flag,󰊓 ,}#W"
set -g window-status-separator " "
set -g pane-border-style "fg=#1e232b"
set -g pane-active-border-style "fg=#53bdfa"
set -g message-style "fg=#0b0e14,bg=#f9af4f"
set -g mode-style "fg=#0b0e14,bg=#1b3a5b"

run '~/.tmux/plugins/tpm/tpm'
